import 'dart:convert';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProfileUpdateRequestEntity {
  String? username;
  String? code;
  String? mail;
  String? gender;
  String? birthday;
  String? location;
  int? numberOfCars;
  String? profile;

  ProfileUpdateRequestEntity({
    this.username,
    this.code,
    this.mail,
    this.gender,
    this.birthday,
    this.location,
    this.numberOfCars,
    this.profile,
  });

  ProfileUpdateRequestEntity.fromJson(Map<String, dynamic> json) {
    username = json['username']?.toString();
    code = json['code']?.toString();
    mail = json['mail']?.toString();
    gender = json['gender']?.toString();
    birthday = json['birthday']?.toString();
    location = json['location']?.toString();
    numberOfCars = json['numberOfCars'];
    profile = json['profile'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['username'] = username;
    data['code'] = code;
    data['mail'] = mail;
    data['gender'] = gender;
    data['birthday'] = birthday;
    data['location'] = location;
    data['numberOfCars'] = numberOfCars;
    data['profile'] = profile;
    return data;
  }

  @override
  toString() => jsonEncode(toJson());
}
